services:
  - type: web
    name: projeto-qrcode-sync-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SYNK_TOKEN
        sync: false
      - key: CITEL_SALES_TABLE
        value: CPPGER
      - key: CITEL_CLIENT_TABLE
        value: CADCLI
      - key: CITEL_SALES_CLIENT_COLUMN
        value: CPG_CODCLI
      - key: CITEL_CLIENT_CODE_COLUMN
        value: CLI_CODCLI
      - key: CITEL_CPF_COLUMN
        value: CLI_C_G_C_
      - key: CITEL_AMOUNT_COLUMN
        value: CPG_VALDOC

  - type: web
    name: projeto-qrcode
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
