services:
  - type: web
    name: projeto-qrcode-sync-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_DRIVER
        value: ODBC Driver 17 for SQL Server
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: CITEL_SALES_TABLE
        value: FATGOR
      - key: CITEL_CPF_COLUMN
        value: CPF
      - key: CITEL_AMOUNT_COLUMN
        value: TOTAL_FATURAMENTO

  - type: web
    name: projeto-qrcode
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
