services:
  - type: web
    name: projeto-qrcode-sync-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MYSQL_DB
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PASS
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: CITEL_SALES_TABLE
        value: FATGOR
      - key: CITEL_CPF_COLUMN
        value: CPF
      - key: CITEL_AMOUNT_COLUMN
        value: TOTAL_FATURAMENTO

  - type: web
    name: projeto-qrcode
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
